#!/bin/bash

td=$(date +%F)
leapdays=0
read -p "Please enter your DOB(YYYY-MM-DD): " pd
#INPUT DRY RUN TEST
if [[ ! ${pd} =~ [0-9]+-[0-9]+-[0-9]+ ]]; then echo -e "\e[41m Please Enter the correct Date Format(YYYY-MM-DD) \e[0m"; fi

birthyr=$(echo ${pd} | cut -d '-' -f1)
birthmon=$(echo ${pd} | cut -d '-' -f2)
curyr=$(echo ${td} | cut -d '-' -f1)
curmon=$(echo ${td} | cut -d '-' -f2)

#LEAP YEAR CALCULATION:
for yr in `seq ${birthyr} ${curyr}`;
do
	leap=$(( ${yr}%4 ))
	if [ ${leap} -eq 0 ];
	then
		leapdays=$(( $leapdays + 1 ))
	fi
	done
#Days calculation:
#==================
f1=$(date -d "$td" +%s)
f2=$(date -d "$pd" +%s)

numdays=$(((${f1} - ${f2}) / 86400 ))
numhrs=$(( ${numdays} * 24 ))
nummins=$(( ${numhrs} * 60 ))
numsecs=$(( ${nummins} * 60 ))

#AGE CALCULATION:
if [ ${birthmon} -gt ${curmon} ];
then
	f3=$(( (${curyr}-1) - ${birthyr} ))
	echo -e "Your Age is : ${f3} Years :: ${curmon} Months :: ${numdays} Days :: ${leapdays} leapdays :: ${numhrs} Hours :: ${nummins} Minutes :: ${numsecs} Seconds"
else
f4=$(( ${curyr} - ${birthyr} ))

echo -e "Your Age is : ${f4} Years :: `expr ${curmon} - ${birthmon}` Months $(date +%d) days :: ${numdays} Days :: ${leapdays} leapdays :: ${numhrs} Hours :: ${nummins} Minutes :: ${numsecs} Seconds"
fi


